##### Importo librerias

In [1]:
# Importo librerias 

import pandas as pd
import seaborn as sns
from sqlalchemy import engine
from pandasql import sqldf
from IPython.display import Image

# Funcion lambda que permite escribir funciones en SQL mas facil
psyqldf = lambda q: sqldf(q, globals())

##### Importo CSV

In [3]:
jugadores = pd.read_csv("players.csv")
clubes = pd.read_csv("clubs.csv")
valuaciones = pd.read_csv("player_valuations.csv")

##### Reviso DataFrames..

In [4]:
jugadores

,player_id,first_name,last_name,name,last_season,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,...,foot,height_in_cm,contract_expiration_date,agent_name,image_url,url,current_club_domestic_competition_id,current_club_name,market_value_in_eur,highest_market_value_in_eur
0,10,Miroslav,Klose,Miroslav Klose,2015,398,miroslav-klose,Poland,Opole,Germany,...,right,184.0,NaN,ASBW Sport Marketing,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/miroslav-klose...,IT1,Società Sportiva Lazio S.p.A.,1000000.0,30000000.0
1,26,Roman,Weidenfeller,Roman Weidenfeller,2017,16,roman-weidenfeller,Germany,Diez,Germany,...,left,190.0,NaN,Neubauer 13 GmbH,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/roman-weidenfe...,L1,Borussia Dortmund,750000.0,8000000.0
2,65,Dimitar,Berbatov,Dimitar Berbatov,2015,1091,dimitar-berbatov,Bulgaria,Blagoevgrad,Bulgaria,...,NaN,NaN,NaN,CSKA-AS-23 Ltd.,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/dimitar-berbat...,GR1,Panthessalonikios Athlitikos Omilos Konstantin...,1000000.0,34500000.0
3,77,NaN,Lúcio,Lúcio,2012,506,lucio,Brazil,Brasília,Brazil,...,NaN,NaN,NaN,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/lucio/profil/s...,IT1,Juventus Football Club,200000.0,24500000.0
4,80,Tom,Starke,Tom Starke,2017,27,tom-starke,East Germany (GDR),Freital,Germany,...,right,194.0,NaN,IFM,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/tom-starke/pro...,L1,FC Bayern München,100000.0,3000000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30375,1166093,Georgios,Konstantakopoulos,Georgios Konstantakopoulos,2023,30120,georgios-konstantakopoulos,NaN,NaN,Greece,...,both,182.0,2026-06-30 00:00:00,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/georgios-konst...,GR1,Athlitiki Enosi Kifisias,100000.0,100000.0
30376,1173042,Djibi,Seck,Djibi Seck,2023,601,djibi-seck,NaN,NaN,Senegal,...,NaN,NaN,2025-06-30 00:00:00,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/djibi-seck/pro...,BE1,Koninklijke Voetbalclub Kortrijk,150000.0,150000.0
30377,1176345,Mahamadou,Nagida,Mahamadou Nagida,2023,273,mahamadou-nagida,Cameroon,Douala,Cameroon,...,left,176.0,2028-06-30 00:00:00,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/mahamadou-nagi...,FR1,Stade Rennais Football Club,150000.0,150000.0
30378,1176866,Motez,Nourani,Motez Nourani,2023,3840,motez-nourani,Tunisia,Sousse,Tunisia,...,right,NaN,2026-06-30 00:00:00,PROhorizons Group,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/motez-nourani/...,TR1,Adana Demirspor Kulübü,250000.0,250000.0
30379,1186012,Bakary,Haidara,Bakary Haidara,2023,968,bakary-haidara,NaN,NaN,Cote d'Ivoire,...,right,NaN,2026-06-30 00:00:00,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/bakary-haidara...,BE1,Koninklijke Voetbal Club Westerlo,350000.0,350000.0

In [5]:
clubes

,club_id,club_code,name,domestic_competition_id,total_market_value,squad_size,average_age,foreigners_number,foreigners_percentage,national_team_players,stadium_name,stadium_seats,net_transfer_record,coach_name,last_season,filename,url
0,105,sv-darmstadt-98,Sportverein Darmstadt 1898 e. V.,L1,NaN,28,26.6,10,35.7,1,Merck-Stadion am Böllenfalltor,17810,€-1.48m,NaN,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/sv-darmstadt-9...
1,11127,ural-ekaterinburg,FK Ural Yekaterinburg,RU1,NaN,27,27.9,15,55.6,6,Yekaterinburg Arena,23000,€-770k,NaN,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/ural-ekaterinb...
2,114,besiktas-istanbul,Beşiktaş Jimnastik Kulübü,TR1,NaN,30,27.7,14,46.7,12,Tüpraş Stadyumu,42590,€-14.50m,NaN,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/besiktas-istan...
3,12,as-rom,Associazione Sportiva Roma,IT1,NaN,27,27.2,18,66.7,17,Olimpico di Roma,73261,+€64.15m,NaN,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/as-rom/startse...
4,148,tottenham-hotspur,Tottenham Hotspur Football Club,GB1,NaN,29,26.3,23,79.3,22,Tottenham Hotspur Stadium,62062,€-154.90m,NaN,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/tottenham-hots...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421,68608,cf-os-belenenses,CF Os Belenenses,PO1,NaN,30,25.7,5,16.7,0,Estádio do Restelo,19980,+-0,NaN,2017,../data/raw/transfermarkt-scraper/2017/clubs.j...,https://www.transfermarkt.co.uk/cf-os-belenens...
422,724,fc-volendam,Football Club Volendam,NL1,NaN,30,22.9,15,50.0,4,Kras Stadion,7384,+€1.80m,NaN,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/fc-volendam/st...
423,800,atalanta-bergamo,Atalanta Bergamasca Calcio S.p.a.,IT1,NaN,25,27.4,18,72.0,16,Gewiss Stadium,21747,+€72.82m,NaN,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/atalanta-berga...
424,979,moreirense-fc,Moreirense Futebol Clube,PO1,NaN,30,26.4,18,60.0,2,Estádio C. J. de Almeida Freitas,6153,€-2.05m,NaN,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/moreirense-fc/...
425,984,west-bromwich-albion,West Bromwich Albion,GB1,NaN,25,27.8,8,32.0,4,The Hawthorns,26850,€-1.35m,NaN,2020,../data/raw/transfermarkt-scraper/2020/clubs.j...,https://www.transfermarkt.co.uk/west-bromwich-...

In [6]:
valuaciones

,player_id,date,market_value_in_eur,current_club_id,player_club_domestic_competition_id
0,405973,2000-01-20,150000,3057,BE1
1,342216,2001-07-20,100000,1241,SC1
2,3132,2003-12-09,400000,126,TR1
3,6893,2003-12-15,900000,984,GB1
4,10,2004-10-04,7000000,398,IT1
...,...,...,...,...,...
464777,1073997,2024-01-08,150000,18,L1
464778,361508,2024-01-10,300000,39,L1
464779,705337,2024-01-10,125000,26459,UKR1
464780,800946,2024-01-10,1000000,79,L1
464781,659225,2024-01-17,100000,5724,DK1

##### CONSULTA SELECT * FROM

In [8]:
# Seleccionamos todo el contenido de la tabla (en este caso todo el contenido del DataFrame que definamos en la consulta)

q = """
SELECT * FROM jugadores
"""

psyqldf(q)

,player_id,first_name,last_name,name,last_season,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,...,foot,height_in_cm,contract_expiration_date,agent_name,image_url,url,current_club_domestic_competition_id,current_club_name,market_value_in_eur,highest_market_value_in_eur
0,10,Miroslav,Klose,Miroslav Klose,2015,398,miroslav-klose,Poland,Opole,Germany,...,right,184.0,None,ASBW Sport Marketing,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/miroslav-klose...,IT1,Società Sportiva Lazio S.p.A.,1000000.0,30000000.0
1,26,Roman,Weidenfeller,Roman Weidenfeller,2017,16,roman-weidenfeller,Germany,Diez,Germany,...,left,190.0,None,Neubauer 13 GmbH,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/roman-weidenfe...,L1,Borussia Dortmund,750000.0,8000000.0
2,65,Dimitar,Berbatov,Dimitar Berbatov,2015,1091,dimitar-berbatov,Bulgaria,Blagoevgrad,Bulgaria,...,None,NaN,None,CSKA-AS-23 Ltd.,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/dimitar-berbat...,GR1,Panthessalonikios Athlitikos Omilos Konstantin...,1000000.0,34500000.0
3,77,None,Lúcio,Lúcio,2012,506,lucio,Brazil,Brasília,Brazil,...,None,NaN,None,None,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/lucio/profil/s...,IT1,Juventus Football Club,200000.0,24500000.0
4,80,Tom,Starke,Tom Starke,2017,27,tom-starke,East Germany (GDR),Freital,Germany,...,right,194.0,None,IFM,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/tom-starke/pro...,L1,FC Bayern München,100000.0,3000000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30375,1166093,Georgios,Konstantakopoulos,Georgios Konstantakopoulos,2023,30120,georgios-konstantakopoulos,None,None,Greece,...,both,182.0,2026-06-30 00:00:00,None,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/georgios-konst...,GR1,Athlitiki Enosi Kifisias,100000.0,100000.0
30376,1173042,Djibi,Seck,Djibi Seck,2023,601,djibi-seck,None,None,Senegal,...,None,NaN,2025-06-30 00:00:00,None,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/djibi-seck/pro...,BE1,Koninklijke Voetbalclub Kortrijk,150000.0,150000.0
30377,1176345,Mahamadou,Nagida,Mahamadou Nagida,2023,273,mahamadou-nagida,Cameroon,Douala,Cameroon,...,left,176.0,2028-06-30 00:00:00,None,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/mahamadou-nagi...,FR1,Stade Rennais Football Club,150000.0,150000.0
30378,1176866,Motez,Nourani,Motez Nourani,2023,3840,motez-nourani,Tunisia,Sousse,Tunisia,...,right,NaN,2026-06-30 00:00:00,PROhorizons Group,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/motez-nourani/...,TR1,Adana Demirspor Kulübü,250000.0,250000.0
30379,1186012,Bakary,Haidara,Bakary Haidara,2023,968,bakary-haidara,None,None,Cote d'Ivoire,...,right,NaN,2026-06-30 00:00:00,None,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/bakary-haidara...,BE1,Koninklijke Voetbal Club Westerlo,350000.0,350000.0

##### WHERE

In [17]:
# Creo un DataFrame de jugadores que esten valuados por mas de $ 100.000 euros y que su origen sea Brasil

q = """
SELECT first_name, country_of_birth, market_value_in_eur FROM jugadores
WHERE country_of_birth = 'Brazil'
AND market_value_in_eur >= 100000
"""

df_ejercicio = psyqldf(q)

In [18]:
df_ejercicio

     first_name country_of_birth  market_value_in_eur
0          None           Brazil             200000.0
1          None           Brazil             400000.0
2         Kevin           Brazil            1250000.0
3          None           Brazil             350000.0
4          None           Brazil             100000.0
...         ...              ...                  ...
1341       None           Brazil            3000000.0
1342       None           Brazil             100000.0
1343       None           Brazil            3000000.0
1344       None           Brazil            9000000.0
1345       None           Brazil             100000.0

[1346 rows x 3 columns]

##### GROUP BY

In [25]:
# Configuro pandas para mostrar numeros en formato completo
pd.set_option('display.float_format', lambda x: '%.3f' % x)

# Creo una tabla que muestre el TOP 10 de valor promedio de mercado de jugadores, agrupado por club actual y ordenado de mayor promedio a menor promedio.

q = """
SELECT 
current_club_name AS club,
AVG(highest_market_value_in_eur) AS promedio_valor
FROM jugadores
GROUP BY 1
ORDER BY promedio_valor DESC
LIMIT 11
"""

top_10_clubes = psyqldf(q)

##### HAVING

In [24]:
# Queremos la misma tabla pero solo con clubes con valor promedio menor a 15,000,000 EUR.
# En este caso aplico HAVING y no WHERE ya que el filtro lo aplicamos sobre el valor ya agrupado, cuando aplicamos WHERE en el primer ejercicio lo hacemos directamente sobre la fila cruda que estamos consultando

q = """
SELECT
current_club_name AS club,
AVG(highest_market_value_in_eur) AS promedio_valor
FROM jugadores
GROUP BY 1
HAVING promedio_valor < 15000000
ORDER BY promedio_valor DESC
LIMIT 11
"""

psyqldf(q)

                                          club  promedio_valor
0                       Sport Lisboa e Benfica    14673387.097
1                    Aston Villa Football Club    14558510.638
2                       RasenBallsport Leipzig    13796568.627
3                        Everton Football Club    13759722.222
4              Nottingham Forest Football Club    13644711.538
5                  Bayer 04 Leverkusen Fußball    12851231.884
6                    Associazione Calcio Milan    12638218.391
7               Real Sociedad de Fútbol S.A.D.    12602985.075
8   Football Club Internazionale Milano S.p.A.    12422747.748
9                         Fulham Football Club    12330970.149
10                     Brentford Football Club    12121022.727

##### LEFT JOIN

In [26]:
# Supongamos que partimos del TOP 10 Clubes segun valuacion promedio de los jugadores.
# Ahora lo que quiero es saber como se llama el estadio de cada uno de estos clubes.
# Para eso vamos a hacer un JOIN entre la tabla que creamos top_10_clubes y la tabla de clubes que se importo al inicio del ejercicio.

clubes

,club_id,club_code,name,domestic_competition_id,total_market_value,squad_size,average_age,foreigners_number,foreigners_percentage,national_team_players,stadium_name,stadium_seats,net_transfer_record,coach_name,last_season,filename,url
0,105,sv-darmstadt-98,Sportverein Darmstadt 1898 e. V.,L1,NaN,28,26.600,10,35.700,1,Merck-Stadion am Böllenfalltor,17810,€-1.48m,NaN,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/sv-darmstadt-9...
1,11127,ural-ekaterinburg,FK Ural Yekaterinburg,RU1,NaN,27,27.900,15,55.600,6,Yekaterinburg Arena,23000,€-770k,NaN,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/ural-ekaterinb...
2,114,besiktas-istanbul,Beşiktaş Jimnastik Kulübü,TR1,NaN,30,27.700,14,46.700,12,Tüpraş Stadyumu,42590,€-14.50m,NaN,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/besiktas-istan...
3,12,as-rom,Associazione Sportiva Roma,IT1,NaN,27,27.200,18,66.700,17,Olimpico di Roma,73261,+€64.15m,NaN,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/as-rom/startse...
4,148,tottenham-hotspur,Tottenham Hotspur Football Club,GB1,NaN,29,26.300,23,79.300,22,Tottenham Hotspur Stadium,62062,€-154.90m,NaN,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/tottenham-hots...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421,68608,cf-os-belenenses,CF Os Belenenses,PO1,NaN,30,25.700,5,16.700,0,Estádio do Restelo,19980,+-0,NaN,2017,../data/raw/transfermarkt-scraper/2017/clubs.j...,https://www.transfermarkt.co.uk/cf-os-belenens...
422,724,fc-volendam,Football Club Volendam,NL1,NaN,30,22.900,15,50.000,4,Kras Stadion,7384,+€1.80m,NaN,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/fc-volendam/st...
423,800,atalanta-bergamo,Atalanta Bergamasca Calcio S.p.a.,IT1,NaN,25,27.400,18,72.000,16,Gewiss Stadium,21747,+€72.82m,NaN,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/atalanta-berga...
424,979,moreirense-fc,Moreirense Futebol Clube,PO1,NaN,30,26.400,18,60.000,2,Estádio C. J. de Almeida Freitas,6153,€-2.05m,NaN,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/moreirense-fc/...
425,984,west-bromwich-albion,West Bromwich Albion,GB1,NaN,25,27.800,8,32.000,4,The Hawthorns,26850,€-1.35m,NaN,2020,../data/raw/transfermarkt-scraper/2020/clubs.j...,https://www.transfermarkt.co.uk/west-bromwich-...

In [28]:
q = """
SELECT
a.*,
b.stadium_name
FROM top_10_clubes a
LEFT JOIN clubes b
ON a.club = b.name
"""

psyqldf(q)

,club,promedio_valor,stadium_name
0,Real Madrid Club de Fútbol,38831521.739,Santiago Bernabéu
1,Manchester City Football Club,35959313.725,Etihad Stadium
2,Futbol Club Barcelona,35056896.552,Olímpic Lluís Companys
3,Paris Saint-Germain Football Club,33982258.065,Parc des Princes
4,Manchester United Football Club,27481923.077,Old Trafford
5,Chelsea Football Club,25117112.676,Stamford Bridge
6,Liverpool Football Club,24879166.667,Anfield
7,FC Bayern München,24535227.273,Allianz Arena
8,Tottenham Hotspur Football Club,21067741.935,Tottenham Hotspur Stadium
9,Arsenal Football Club,20642361.111,Emirates Stadium
10,Club Atlético de Madrid S.A.D.,18535344.828,Civitas Metropolitano